### ISSUE TITLE
V1

### ISSUE THREAD

**Issue by tomtomcrypto** [telosnetwork/telos-monitor#1]
### TASKS

**SYSTEM CONTRACTS** 

- [x] Distribution from reserve via exrsrv.tf::pay 
- [x] Price oracle datapoints being updated 
- [x] RNG oracle lifecycle via Native Consumer 
- [x] RNG EVM Bridge TLOS balance
- [x] RAM of free.tf (20% free)
- [x] CPU/NET/RAM of eosio.evm (50% free)
- [x] Limit of whitelisted accounts in free.tf whitelist and conflist 
- [x] Make sure the approved accounts are not about to run out, accounts.tf is the one that creates free accounts for app.telos.net/api.telos.net 

**ENDPOINTS**

- [x] Hyperion endpoints availability 
- [x] RPC endpoints availability
- [x] #2

**SERVICES** 

- [x] HTTP services availability (explorers, docs, telos.net, wallet, …) 

### REPORTING

- [x] Postgres database + REST API
- [x] Mailer implementation
- [x] Quasar + Pinia Frontend
